# Generated by Django 4.0.6 on 2022-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('nim', models.IntegerField()),
                ('alamat', models.TextField(max_length=100)),
                ('jk', models.CharField(choices=[('None', '?'), ('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='None', max_length=20)),
                ('status', models.CharField(choices=[('None', '?'), ('Aktif', 'aktif'), ('Transfer', 'transfer')], default='None', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
